
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jamshad
 */
public class Edit_Exchange extends javax.swing.JFrame {

    /**
     * Creates new form Edit_bus
     */
    public Edit_Exchange() {
        initComponents();
        Fillcombo();
    }
private void Fillcombo()
    {
        try{
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");
            String z="select * from holding";
            PreparedStatement ps=con.prepareStatement(z);
          
            ResultSet rs=ps.executeQuery();
            while (rs.next())
            {
            String reg=rs.getString("exchange_name");
            exchange_name.addItem(reg);
            }
            
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);   
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        combo3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        id1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        exchange_name = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("edit exchange");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 200, 20));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel4.setText("Exchange type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        update.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 110, 30));

        delete.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 110, 30));

        combo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bitcoin", "Altcoin" }));
        getContentPane().add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 230, 30));

        jLabel6.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel6.setText("USD Amount:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        search.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 90, 30));

        id1.setEditable(false);
        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });
        getContentPane().add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 40, 30));

        jLabel7.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        jLabel7.setText("ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 230, 30));

        getContentPane().add(exchange_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light_faded_background_85547_1600x1200.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        setBounds(0, 0, 645, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");

            String sql=("update holding set exchange_name=?, usd_amount=?, type=? where id=?");
            PreparedStatement ps=cn.prepareStatement(sql);
            ps.setString(1,exchange_name.getSelectedItem().toString());
            ps.setString(2,text2.getText());
            ps.setString(3,combo3.getSelectedItem().toString());
            ps.setString(4,id1.getText());
            

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Exchange details updated successfully");

        } catch (SQLException ex) {
            Logger.getLogger(Add_Exchange.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");

            String sql=("delete from holding where id=?");
            PreparedStatement ps=cn.prepareStatement(sql);
            ps.setString(1,id1.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Exchange deleted successfully!");

        } catch (SQLException ex) {
            Logger.getLogger(Add_Exchange.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");
            String zn="select * from holding where exchange_name=? ORDER BY id DESC limit 1";
            PreparedStatement ps=con.prepareStatement(zn);

            ps.setString(1,exchange_name.getSelectedItem().toString());
            ResultSet rs=ps.executeQuery();
            if (rs.next())
            {
                id1.setText(rs.getString("id"));
                exchange_name.setSelectedItem(rs.getString("exchange_name"));
                text2.setText(rs.getString("usd_amount"));
             
                combo3.setSelectedItem(rs.getString("type"));
              
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Not Found!");
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Exchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo3;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox exchange_name;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton search;
    private javax.swing.JTextField text2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
