
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Exchange_Status extends javax.swing.JFrame {
    private Object jDateChooser1;

 
    public Exchange_Status() {
        initComponents();
        Fillcombo();
    }
        private void Fillcombo()
    {
        try{
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");
            String z="select DISTINCT exchange_name from holding";
            PreparedStatement ps=con.prepareStatement(z);
          
            ResultSet rs=ps.executeQuery();
            while (rs.next())
            {
            String reg=rs.getString("exchange_name");
            Ex_name.addItem(reg);
            }
            
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);   
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        Ex_name = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        hold_data = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("your holdings");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 210, 10));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exchange Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        search.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        search.setText("Select Exchange");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 180, 30));

        Ex_name.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        Ex_name.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(Ex_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 230, 30));

        hold_data.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        hold_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exchange Name", "Coin Name", "Total Amount", "Amount in USD", "Add Date", "Duration", "API Key"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hold_data);
        if (hold_data.getColumnModel().getColumnCount() > 0) {
            hold_data.getColumnModel().getColumn(0).setResizable(false);
            hold_data.getColumnModel().getColumn(1).setResizable(false);
            hold_data.getColumnModel().getColumn(2).setResizable(false);
            hold_data.getColumnModel().getColumn(3).setResizable(false);
            hold_data.getColumnModel().getColumn(4).setResizable(false);
            hold_data.getColumnModel().getColumn(5).setResizable(false);
            hold_data.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 770, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstraction_sharp_figure_101902_1920x1080.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 820, 530));

        setBounds(0, 0, 835, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try {
            Connection cnn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold", "root", "");
            String sql="select * from holding where exchange_name=? ORDER BY id DESC";
            PreparedStatement ps=cnn.prepareStatement(sql);
            ps.setString(1,Ex_name.getSelectedItem().toString());
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)hold_data.getModel();
            tm.setRowCount(0);
            
            while (rs.next())
            {
                Object o[]={rs.getString("exchange_name"),rs.getString("coin_name"),rs.getString("tot_amount"),rs.getString("usd_amount"),rs.getString("add_date"),rs.getString("hold_dur")
                ,rs.getString("api_key")};
                tm.addRow(o);
            }
        } catch (SQLException ex) {
            //Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exchange_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exchange_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exchange_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exchange_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exchange_Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ex_name;
    private javax.swing.JTable hold_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
