
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Holdcrypto extends javax.swing.JFrame {

    /**
     * Creates new form Holdcrypto
     */
    public Holdcrypto() {
        initComponents();
        Fillcombo();
    }
    private void Fillcombo()
    {
        try{
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");
            String z="select * from exchange";
            PreparedStatement ps=con.prepareStatement(z);
          
            ResultSet rs=ps.executeQuery();
            while (rs.next())
            {
            String reg=rs.getString("name");
            ex_name.addItem(reg);
            }
            
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);   
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        ex_name = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        combo3 = new javax.swing.JComboBox();
        text2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        coin_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        usd_amount = new javax.swing.JTextField();
        add_date = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        api_key = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        hold_dur = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(ex_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Exchange name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Crypto Holding:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 230, 30));

        jButton1.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        jButton1.setText("Fill Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 32, 160, 10));

        combo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bitcoin", "Alt Coin" }));
        getContentPane().add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 30));

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 230, 30));

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, -1));

        jLabel6.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Amount:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Coin Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));
        getContentPane().add(coin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        jLabel8.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Duration:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 30));
        getContentPane().add(usd_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 230, 30));
        getContentPane().add(add_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 230, 30));

        jLabel9.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Amount in USD:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        jLabel13.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("API Key:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, 20));
        getContentPane().add(api_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 230, 30));

        jButton2.setFont(new java.awt.Font("ROG Fonts", 1, 12)); // NOI18N
        jButton2.setText("ADD HOLDING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 150, 30));

        hold_dur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HODL", "Short Term", "For Exchange" }));
        hold_dur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hold_durActionPerformed(evt);
            }
        });
        getContentPane().add(hold_dur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 230, 30));

        jLabel10.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Add date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Please click on the\n\"Fill Details\"\nbutton to generate\nthe amount\navailable in the \nexchange.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 170, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blur_background_pink_orange_light_73376_1280x720.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 540));

        setBounds(0, 0, 600, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");
             String zn="select * from exchange where name=? ORDER BY id DESC limit 1";
            PreparedStatement ps=con.prepareStatement(zn);
           
            ps.setString(1,ex_name.getSelectedItem().toString());
            ResultSet rs=ps.executeQuery();
            if (rs.next())
            {
                
                text2.setText(rs.getString("tot_amount"));
                combo3.setSelectedItem(rs.getString("type"));

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Not Found");
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3306/crypto_hold","root","");

            String sql="insert into holding values(?,?,?,?,?,?,?,?,?,now())";
            PreparedStatement ps=cn.prepareStatement(sql);
            ps.setString(1,null);
            ps.setString(2,ex_name.getSelectedItem().toString());
            ps.setString(3,text2.getText());
  
            ps.setString(4,combo3.getSelectedItem().toString());
            ps.setString(5,coin_name.getText());
            ps.setString(6,usd_amount.getText());
            java.sql.Date d1=new java.sql.Date(add_date.getDate().getTime());
            ps.setDate(7, d1);
            ps.setString(8,hold_dur.getSelectedItem().toString());

            ps.setString(9,api_key.getText());
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Crypto added successfully");
            
            text2.setText(null);
            coin_name.setText(null);
            usd_amount.setText(null);
       
            api_key.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(Holdcrypto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hold_durActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hold_durActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hold_durActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Holdcrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Holdcrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Holdcrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Holdcrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Holdcrypto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser add_date;
    private javax.swing.JTextField api_key;
    private javax.swing.JTextField coin_name;
    private javax.swing.JComboBox combo3;
    private javax.swing.JComboBox ex_name;
    private javax.swing.JComboBox hold_dur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField usd_amount;
    // End of variables declaration//GEN-END:variables
}
